language: java

sudo: false

before_install:
  - 'ls -a'
  - 'pwd'
  - 'curl -JORL https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u202-b08/OpenJDK8U-jdk_x64_linux_hotspot_8u202b08.tar.gz'
  - 'tar -xf OpenJDK8U-jdk_x64_linux_hotspot_8u202b08.tar.gz'
  - 'export JAVA_HOME=$PWD/jdk8u202-b08'
  - 'export PATH=$JAVA_HOME/bin:$PATH'
  - 'java -version'
#  - 'sudo update-alternatives --config java'
  - './gradlew clean'

env:
  global:
  - checkstyleaddons_jdk7_java=/usr/lib/jvm/java-7-openjdk-amd64/bin/java
  - checkstyleaddons_jdk7_javac=/usr/lib/jvm/java-7-openjdk-amd64/bin/javac
  - checkstyleaddons_jdk7_javadoc=/usr/lib/jvm/java-7-openjdk-amd64/bin/javadoc

install: true
script:
  - ./gradlew build site

after_success:
  - ./gradlew jacocoTestReport coveralls

cache:
  directories:
  - ~/.gradle

branches:
  only:
  - master
