language: java

jdk:
  - oraclejdk8

sudo: false

before_install:
  - ls -a
  - pwd
#  - sudo update-alternatives --config java
  - ./gradlew clean

# Update JDK8 to latest version available for Travis
#addons:
#  apt:
#    packages:
#      - oracle-java8-installer

env:
  global:
  - checkstyleaddons_jdk7_java=/usr/lib/jvm/java-7-openjdk-amd64/bin/java
  - checkstyleaddons_jdk7_javac=/usr/lib/jvm/java-7-openjdk-amd64/bin/javac
  - checkstyleaddons_jdk7_javadoc=/usr/lib/jvm/java-7-openjdk-amd64/bin/javadoc

install: true
script:
  - ./gradlew build site

after_success:
  - ./gradlew jacocoTestReport coveralls

cache:
  directories:
  - ~/.gradle

branches:
  only:
  - master
