language: java

jdk:
  - openjdk8
  - oraclejdk8

sudo: true

before_install:
  - ls -a
  - pwd
  - sudo update-alternatives --config java
  - ./gradlew clean

env:
  global:
  - checkstyleaddons_jdk6_javac=/usr/lib/jvm/java-6-openjdk-amd64/bin/javac
  - checkstyleaddons_jdk6_javadoc=/usr/lib/jvm/java-6-openjdk-amd64/bin/javadoc
  - checkstyleaddons_jdk7_javac=/usr/lib/jvm/java-7-openjdk-amd64/bin/javac
  - checkstyleaddons_jdk7_javadoc=/usr/lib/jvm/java-7-openjdk-amd64/bin/javadoc

script:
  - ./gradlew check xcheck site

after_success:
  - ./gradlew jacocoTestReport coveralls

cache:
  directories:
  - ~/.gradle

branches:
  only:
  - master
