language: java

jdk:
  - openjdk7
  - oraclejdk7

sudo: false

before_install:
  - ls -a
  - pwd
#  - sudo update-alternatives --config java

env:
  global:
  - checkstyleaddons_jdk6_javac=/usr/lib/jvm/java-6-openjdk-amd64/bin/javac

script:
  - ./gradlew build

after_success:
  - ./gradlew jacocoTestReport coveralls

cache:
  directories:
  - ~/.gradle

branches:
  only:
  - master
