language: java

jdk:
  - openjdk7
  - oraclejdk7

before_install:
  - ls -a
  - pwd
#  - sudo update-alternatives --config java

env:
  -
  - checkstyleaddons_deps=cs6.1.1
  - checkstyleaddons_deps=java6 checkstyleaddons_jdk6_javac=/usr/lib/jvm/java-6-openjdk-amd64/bin/javac

after_success:
  - ./gradlew jacocoTestReport coveralls

cache:
  directories:
  - ~/.gradle

#branches:
#  only:
#  - master
