language: java

jdk:
  - openjdk7
  - oraclejdk7

env:
  global:
    - checkstyleaddons_jdk6_javac=/usr/lib/jvm/java-6-openjdk-amd64/bin/javac
# TODO: compile with oracle jdk6 when build jdk is oraclejdk7

before_install:
  - ls -a
  - pwd
#  - sudo update-alternatives --config java

after_success:
  - ./gradlew jacocoTestReport coveralls
