# Jekyll configuration

name: Checkstyle Addons
description: Additional Checkstyle Checks

# enable emoticons
gems:
  - jemoji

# website address
url: http://checkstyle-addons.thomasjensen.com/

# baseurl will often be '', but for a project page on gh-pages, it needs to
# be the project name.
# *** IMPORTANT: If your local "jekyll serve" throws errors change this to '' or
#     run it like so: jekyll serve --baseurl=''
baseurl: ''

# This can be '' to hide the Github nav button
github: 'checkstyle-addons/checkstyle-addons'

# Set this to your UA-# value, or '' to disable the block completely
gaaccount: 'UA-23698164-6'


permalink: /:year/:month/:title
#paginate: 10
future: true

exclude: ['README.md', 'LICENSE', '*.iml', 'build', 'gradle']

# checkstyle-addons custom variables
latest_version: '5.2.0'
latest_major: '5'
# next line gives the Checkstyle version used by the default depconfig
latest_version_checkstyle: '8.0'
# next line is the highest Checkstyle version tested by the unit tests
latest_checkstyle_tested: '8.2'

# links to external websites that are used in multiple places throughout the site
link_bintray: 'https://bintray.com/checkstyle-addons/checkstyle-addons/checkstyle-addons/view'
link_mavencentral: 'http://search.maven.org/#search%7Cgav%7C1%7Cg%3Acom.thomasjensen.checkstyle.addons'

link_cs_home: 'http://checkstyle.sourceforge.net/'
link_cs_anttask: 'http://checkstyle.sourceforge.net/anttask.html'
link_cs_check_translation: 'http://checkstyle.sourceforge.net/config_misc.html#Translation'
link_cs_check_uniqueprops: 'http://checkstyle.sourceforge.net/config_misc.html#UniqueProperties'
link_cs_checker: 'http://checkstyle.sourceforge.net/config.html#Checker'
link_cs_filesetcheck: 'http://checkstyle.sourceforge.net/writingchecks.html#Writing_FileSetChecks'
link_cs_properties: 'http://checkstyle.sourceforge.net/config.html#Properties'
link_cs_releasenotes: 'http://checkstyle.sourceforge.net/releasenotes.html'
link_cs_treewalker: 'http://checkstyle.sourceforge.net/config.html#TreeWalker'
link_cs_type_boolean: 'http://checkstyle.sourceforge.net/property_types.html#boolean'
link_cs_type_integer: 'http://checkstyle.sourceforge.net/property_types.html#integer'
link_cs_type_regexp: 'http://checkstyle.sourceforge.net/property_types.html#regexp'
link_cs_type_string: 'http://checkstyle.sourceforge.net/property_types.html#string'
link_cs_type_stringset: 'http://checkstyle.sourceforge.net/property_types.html#stringSet'

link_sq_home: 'http://www.sonarqube.org/'
link_sq_relupgradenotes: 'http://docs.sonarqube.org/display/SONAR/Upgrading#Upgrading-ReleaseUpgradeNotes'
link_sq_csplugin: 'https://github.com/checkstyle/sonar-checkstyle'
