# Jekyll configuration

name: Checkstyle Addons
description: Additional Checkstyle Checks

# Plugins from the whitelist at https://github.com/github/pages-gem/blob/master/lib/github-pages/plugins.rb
# enable emoticons
plugins:
  - jemoji
  - jekyll-sitemap

# website address
url: https://checkstyle-addons.thomasjensen.com

# baseurl will often be '', but for a project page on gh-pages, it needs to
# be the project name.
# *** IMPORTANT: If your local "jekyll serve" throws errors change this to '' or
#     run it like so: jekyll serve --baseurl=''
baseurl: ''

# This can be '' to hide the Github nav button
github: 'checkstyle-addons/checkstyle-addons'

# Set this to your UA-# value, or '' to disable the block completely
gaaccount: ''


permalink: /:year/:month/:title:output_ext
#paginate: 10
future: true

exclude: ['README.md', 'LICENSE', '*.iml', 'build', 'gradle', 'out']

# Exclude Javadocs from the sitemap
defaults:
  -
    scope:
      path: "*/apidocs/"
    values:
      sitemap: false

# checkstyle-addons custom variables
latest_version: '7.0.0'
latest_major: '7'
# next line gives the Checkstyle version used by the default depconfig
latest_version_checkstyle: '10.0'
latest_version_checkstyle_java7: '6.4.1'
latest_version_checkstyle_java8a: '8.0'
latest_version_checkstyle_java8b: '8.21'
# next line is the highest Checkstyle version tested by the unit tests
latest_checkstyle_tested: '10.0'

# links to external websites that are used in multiple places throughout the site
link_mavencentral: 'https://search.maven.org/#search%7Cgav%7C1%7Cg%3Acom.thomasjensen.checkstyle.addons'
link_central_download: 'https://repo1.maven.org/maven2/com/thomasjensen/checkstyle/addons'

link_cs_home: 'https://checkstyle.org/'
link_cs_anttask: 'https://checkstyle.org/anttask.html'
link_cs_check_translation: 'https://checkstyle.org/config_misc.html#Translation'
link_cs_check_uniqueprops: 'https://checkstyle.org/config_misc.html#UniqueProperties'
link_cs_checker: 'https://checkstyle.org/config.html#Checker'
link_cs_filesetcheck: 'https://checkstyle.org/writingchecks.html#Writing_FileSetChecks'
link_cs_properties: 'https://checkstyle.org/config.html#Properties'
link_cs_releasenotes: 'https://checkstyle.org/releasenotes.html'
link_cs_treewalker: 'https://checkstyle.org/config.html#TreeWalker'
link_cs_type_boolean: 'https://checkstyle.org/property_types.html#boolean'
link_cs_type_integer: 'https://checkstyle.org/property_types.html#integer'
link_cs_type_regexp: 'https://checkstyle.org/property_types.html#regexp'
link_cs_type_string: 'https://checkstyle.org/property_types.html#string'
link_cs_type_stringset: 'https://checkstyle.org/property_types.html#stringSet'

link_sq_home: 'https://www.sonarqube.org/'
link_sq_relupgradenotes: 'https://docs.sonarqube.org/display/SONAR/Upgrading#Upgrading-ReleaseUpgradeNotes'
link_sq_csplugin: 'https://github.com/checkstyle/sonar-checkstyle'
