name: build

on: [push, pull_request, workflow_dispatch]

jobs:
    build:
        runs-on: ubuntu-latest
        container:
            image: gradle:7.4.1-jdk11
            env:
                DEBIAN_FRONTEND: noninteractive
                checkstyleaddons_jdk7_java: /usr/lib/jvm/zulu7/bin/java
                checkstyleaddons_jdk7_javac: /usr/lib/jvm/zulu7/bin/javac
                checkstyleaddons_jdk7_javadoc: /usr/lib/jvm/zulu7/bin/javadoc
                checkstyleaddons_jdk8_java: /usr/lib/jvm/zulu8/bin/java
                checkstyleaddons_jdk8_javac: /usr/lib/jvm/zulu8/bin/javac
                checkstyleaddons_jdk8_javadoc: /usr/lib/jvm/zulu8/bin/javadoc
        steps:
            - name: upgrade-git
              run: |
                  apt-get update -y
                  apt-get install -y software-properties-common
                  add-apt-repository -y ppa:git-core/ppa
                  apt-get update
                  apt-get install -y git

            - name: add-jdk7
              run: |
                  apt-get -y install gnupg
                  apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 0xB1998361219BD9C9
                  curl -LO https://cdn.azul.com/zulu/bin/zulu-repo_1.0.0-3_all.deb
                  apt-get install ./zulu-repo_1.0.0-3_all.deb
                  apt-get update
                  apt-get install -y zulu7-jdk

            - name: add-jdk8
              run: |
                  apt-get install -y zulu8-jdk

            - name: versions
              run: |
                  echo PATH=${PATH}
                  git --version
                  echo JAVA_HOME=${JAVA_HOME}
                  ls -l ${JAVA_HOME}/bin/java
                  java -version
                  ls -l ${checkstyleaddons_jdk7_java}
                  ${checkstyleaddons_jdk7_java} -version
                  ls -l ${checkstyleaddons_jdk8_java}
                  ${checkstyleaddons_jdk8_java} -version

            - uses: actions/checkout@v2

            - name: build
              run: |
                  gradle clean
                  gradle build site
                  gradle jacocoTestReport

            - name: codecov
              env:
                  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
              run: |
                  curl -LsS --output codecov.sh https://codecov.io/bash
                  chmod a+x codecov.sh
                  bash ./codecov.sh -t ${CODECOV_TOKEN} -s build/reports/jacoco/test
