#
# Checkstyle-Addons - Additional Checkstyle checks
# Copyright (c) 2015-2024, the Checkstyle Addons contributors
#
# This program is free software: you can redistribute it and/or modify it under the
# terms of the GNU General Public License, version 3, as published by the Free
# Software Foundation.
#
# This program is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with this
# program.  If not, see <http://www.gnu.org/licenses/>.
#

name: build

on: [push, pull_request, workflow_dispatch]

jobs:
    build:
        runs-on: ubuntu-latest
        container:
            image: gradle:8.14-jdk17
            env:
                DEBIAN_FRONTEND: noninteractive
        steps:
            - name: upgrade-git
              run: |
                  apt-get update -y
                  apt-get install -y software-properties-common apt-transport-https
                  add-apt-repository -y ppa:git-core/ppa
                  apt-get update
                  apt-get install -y git

            - name: add-jdk7
              run: |
                  apt-get -y install gnupg
                  apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 0xB1998361219BD9C9
                  curl -LO https://cdn.azul.com/zulu/bin/zulu-repo_1.0.0-3_all.deb
                  apt-get install ./zulu-repo_1.0.0-3_all.deb
                  apt-get update
                  apt-get install -y zulu7-jdk

            - name: add-jdk8
              run: |
                  curl -L -o - https://packages.adoptium.net/artifactory/api/gpg/key/public | gpg --dearmor | tee /etc/apt/trusted.gpg.d/adoptium.gpg > /dev/null
                  echo "deb https://packages.adoptium.net/artifactory/deb $(awk -F= '/^VERSION_CODENAME/{print$2}' /etc/os-release) main" | tee /etc/apt/sources.list.d/adoptium.list
                  apt-get update
                  apt-get install -y temurin-8-jdk

            - name: add-jdk11
              run: |
                  apt-get install -y temurin-11-jdk

            - uses: actions/checkout@v4

            - name: versions
              run: |
                  echo PATH=${PATH}
                  git --version
                  echo JAVA_HOME=${JAVA_HOME}
                  ls -l ${JAVA_HOME}/bin/java
                  java -version
                  ls -l /usr/lib/jvm/zulu7/bin
                  /usr/lib/jvm/zulu7/bin/java -version
                  ls -l /usr/lib/jvm/temurin-8-jdk-amd64/bin
                  /usr/lib/jvm/temurin-8-jdk-amd64/bin/java -version
                  ls -l /usr/lib/jvm/temurin-11-jdk-amd64/bin
                  /usr/lib/jvm/temurin-11-jdk-amd64/bin/java -version
                  gradle javaToolchains

            - name: build
              run: |
                  gradle --warning-mode all clean
                  gradle --warning-mode all build site
                  gradle --warning-mode all jacocoTestReport

            - name: codecov
              env:
                  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
              run: |
                  curl -LsS --output codecov.sh https://codecov.io/bash
                  chmod a+x codecov.sh
                  bash ./codecov.sh -t ${CODECOV_TOKEN} -s build/reports/jacoco/test
